### ISSUE TITLE
RT should tell about the failed request and http status code.

### ISSUE THREAD

**Issue by sahilb** [w3c/resource-timing#22] opened 2015-05-06 22:24 UTC
Is there a reason why failed requests are not being listed in the entries? 

ForEach resource, it could iterate as:
1) if the resource load successfully, then capture the metrics as mentioned in the spec.
2) if the resource load failed, capture the reasons why it did not like HTTP status code,etc.

**Comment by igrigorik** [comment] 2015-05-06 22:25
Duplicate of https://github.com/w3c/resource-timing/issues/12 - please see that thread.

**Closed by igrigorik** 2015-05-06 22:25 UTC

**Comment by vaibhavtripathi** [comment] 2016-12-27 12:35
@igrigorik Can you elaborate on how this is issue is a duplicate of #12? As far as I could understand, #12 does specify what resources should be a part of the resource timing entires but I could not see sufficient markers by which a developer can distinguish between resources that succeeded and those that failed. If that is the case, this issue seems to be a bit different from what is discussed in #12. @nicjansma's comment "There should probably also be a new field on the PerformanceResourceTiming interface to indicate that it is a failure (and possibly, some classification on why)." is more relevant to this but I do not see any follow ups to that.

**Comment by igrigorik** [comment] 2016-12-27 14:59
@vaibhavtripathi see https://github.com/w3c/resource-timing/issues/12#issuecomment-248445564. There is still a discussion to be had about additional status codes.. and we should open a new issue for that.

 (and if we're willing to go down this path)

**Comment by vaibhavtripathi** [comment] 2016-12-28 05:18
@igrigorik Thanks a lot. I had missed that particular comment for some reason.
