### ISSUE TITLE
Transition Level 2 to CR

### ISSUE THREAD

**Issue by igrigorik** [w3c/resource-timing#71] opened 2016-10-13 23:29 UTC
- **Known / outstanding spec issues**
  - [x] https://github.com/w3c/resource-timing/milestone/2
- **Web platform tests**
  - [x] https://github.com/w3c/web-platform-tests/pull/402
  - [x] https://github.com/w3c/web-platform-tests/pull/2919
  - [x] https://github.com/w3c/web-platform-tests/pull/4266
- **Privacy and security**
  - [x] https://w3c.github.io/resource-timing/#privacy-security
- **Implementations**
  - [x] Chrome: [size attributes: M54+](https://www.chromestatus.com/feature/6549060404117504); [workerStart: M46+](https://www.chromestatus.com/feature/5767679470206976); wip: [nextHopProtocol](https://bugs.chromium.org/p/chromium/issues/detail?id=454818).
  - [x] Firefox: [M45+](https://bugzilla.mozilla.org/show_bug.cgi?id=1154309)
  - [ ] Edge: missing support for [*size, protocol, secureConnectionStart](https://developer.microsoft.com/en-us/microsoft-edge/platform/catalog/?q=specName%3Aresource-timing)
  - [ ] Safari: no public signals
- [x] Update acknowledgement section

**Comment by plehegar** [comment] 2016-11-03 15:40
FPWD got published today. Will touch base in 2/3 weeks to move to CR.

**Comment by huynhhaiof** [comment] 2016-12-22 18:55
![game hay co tren c ng phat l c](https://cloud.githubusercontent.com/assets/24368116/21436765/c3eff80e-c8b2-11e6-8d60-cc1f0c237e35.jpg)
https://phatloc.vtcgame.vn

**Comment by yoavweiss** [comment] 2019-01-11 07:05
OK, so the current state of affairs:
* Open issues
[ ] https://github.com/w3c/resource-timing/issues/195
* Pending WPTs
[ ] https://github.com/web-platform-tests/wpt/pull/13518
[ ] https://github.com/web-platform-tests/wpt/pull/13823
* WPT status
[![WPT Chrome](https://wpt-badge.glitch.me/?product=chrome&prefix=/resource-timing)](https://wpt.fyi/results/resource-timing)
[![WPT Edge](https://wpt-badge.glitch.me/?product=edge&prefix=/resource-timing)](https://wpt.fyi/results/resource-timing)
[![WPT Firefox](https://wpt-badge.glitch.me/?product=firefox&prefix=/resource-timing)](https://wpt.fyi/results/resource-timing)
[![WPT Safari](https://wpt-badge.glitch.me/?product=safari&prefix=/resource-timing)](https://wpt.fyi/results/resource-timing)

**Comment by igrigorik** [comment] 2019-01-11 19:42
note: WPT badges don't seem to reflect the actual status — something weird with caching?

**Comment by yoavweiss** [comment] 2019-01-11 21:49
> note: WPT badges don't seem to reflect the actual status — something weird with caching?

weird. They worked fine earlier today...

**Comment by yoavweiss** [comment] 2019-02-10 20:12
As discussed in the latest F2F, I looked into which tests are currently failing in Firefox and Safari to get us to 2 passing implementations for each test. The list is:
* [ ] [buffer-full-add-entries-during-callback-that-drop.html](https://wpt.fyi/results/resource-timing/buffer-full-add-entries-during-callback-that-drop.html?label=master&product=chrome%5Bexperimental%5D&product=edge&product=firefox%5Bexperimental%5D&product=safari%5Bexperimental%5D&aligned)
* [ ] [buffer-full-add-then-clear.html](https://wpt.fyi/results/resource-timing/buffer-full-add-then-clear.html?label=master&product=chrome%5Bexperimental%5D&product=edge&product=firefox%5Bexperimental%5D&product=safari%5Bexperimental%5D&aligned)
* [ ] [buffer-full-then-increased.html](https://wpt.fyi/results/resource-timing/buffer-full-then-increased.html?label=master&product=chrome%5Bexperimental%5D&product=edge&product=firefox%5Bexperimental%5D&product=safari%5Bexperimental%5D&aligned)
* [ ] [no-entries-for-cross-origin-css-fetched.sub.html](https://wpt.fyi/results/resource-timing/no-entries-for-cross-origin-css-fetched.sub.html?label=master&product=chrome%5Bexperimental%5D&product=edge&product=firefox%5Bexperimental%5D&product=safari%5Bexperimental%5D&aligned)
* [ ] [resource_connection_reuse.https.html](https://wpt.fyi/results/resource-timing/resource_connection_reuse.https.html?label=master&product=chrome%5Bexperimental%5D&product=edge&product=firefox%5Bexperimental%5D&product=safari%5Bexperimental%5D&aligned)
* [ ] [resource_connection_reuse_mixed_content.html](https://wpt.fyi/results/resource-timing/resource_connection_reuse_mixed_content.html?label=master&product=chrome%5Bexperimental%5D&product=edge&product=firefox%5Bexperimental%5D&product=safari%5Bexperimental%5D&aligned)
* [ ] [resource_connection_reuse_mixed_content_redirect.html](https://wpt.fyi/results/resource-timing/resource_connection_reuse_mixed_content_redirect.html?label=master&product=chrome%5Bexperimental%5D&product=edge&product=firefox%5Bexperimental%5D&product=safari%5Bexperimental%5D&aligned)
* [ ] [resource_initiator_types.html](https://wpt.fyi/results/resource-timing/resource_initiator_types.html?label=master&product=chrome%5Bexperimental%5D&product=edge&product=firefox%5Bexperimental%5D&product=safari%5Bexperimental%5D&aligned)
* [ ] [resource_reparenting.html](https://wpt.fyi/results/resource-timing/resource_reparenting.html?label=master&product=chrome%5Bexperimental%5D&product=edge&product=firefox%5Bexperimental%5D&product=safari%5Bexperimental%5D&aligned)
* [ ] [resource_timing_cross_origin_redirect_chain.html](https://wpt.fyi/results/resource-timing/resource_timing_cross_origin_redirect_chain.html?label=master&product=chrome%5Bexperimental%5D&product=edge&product=firefox%5Bexperimental%5D&product=safari%5Bexperimental%5D&aligned) - "startTime == fetchStart in cross-origin redirect."
* [ ] [supported_resource_type.any.html](https://wpt.fyi/results/resource-timing/supported_resource_type.any.html?label=master&product=chrome%5Bexperimental%5D&product=edge&product=firefox%5Bexperimental%5D&product=safari%5Bexperimental%5D&aligned)
* [ ] [supported_resource_type.any.worker.html](https://wpt.fyi/results/resource-timing/supported_resource_type.any.worker.html?label=master&product=chrome%5Bexperimental%5D&product=edge&product=firefox%5Bexperimental%5D&product=safari%5Bexperimental%5D&aligned)

@cvazac - Can you confirm that all buffering related ones will be fixed by https://bugs.webkit.org/show_bug.cgi?id=193213? @rniwa - would it be possible to land that fix?

@rniwa and @mstange - can your teams prioritize the work required to fix these issues and pass the tests?

**Comment by cvazac** [comment] 2019-02-14 15:34
@yoavweiss I confirm! :)

**Comment by yoavweiss** [comment] 2019-03-07 08:10
> @yoavweiss I confirm! :)

Looks like it didn't make the latest STP, but I just confirmed that the latest webkit build passes the tests 🎉

**Comment by noamr** [comment] 2022-07-18 15:16
@yoavweiss what does this require now?

**Closed** 2022-07-18 15:36 UTC
Labels: w3c
